const data = {
  products: [
    {
      slug: 1,
      name: " Олимпийка ",
      brand: "Mark Formelle",
      price: 2574,
      rating: "3.1",
      numReview: 25,
      coutnInStocks: 8,
      img: "https://a.lmcdn.ru/img600x866/M/P/MP002XW0BH42_16308905_1_v1_2x.jpg",
      description:
        "\n        Олимпийка\n        Mark Formelle.\n        \n      ",
    },
    {
      slug: 2,
      name: " Худи ",
      brand: "Pinko",
      price: 32600,
      rating: "4.9",
      numReview: 3,
      coutnInStocks: 18,
      img: "https://a.lmcdn.ru/img600x866/R/T/RTLABA428901_16258409_1_v1_2x.jpg",
      description: "\n        Худи\n        Pinko.\n        \n      ",
    },
    {
      slug: 3,
      name: " Толстовка ",
      brand: "Pinko",
      price: 37600,
      rating: "3.2",
      numReview: 29,
      coutnInStocks: 3,
      img: "https://a.lmcdn.ru/img600x866/R/T/RTLABA718301_16226138_1_v1_2x.jpg",
      description: "\n        Толстовка\n        Pinko.\n        \n      ",
    },
    {
      slug: 4,
      name: " Джинсы MAR",
      brand: "Mango",
      price: 4999,
      rating: "4.3",
      numReview: 13,
      coutnInStocks: 9,
      img: "https://a.lmcdn.ru/img600x866/R/T/RTLAAZ138401_16041881_1_v1.jpg",
      description: "\n        Джинсы\n        Mango.\n        \n      ",
    },
    {
      slug: 5,
      name: " Куртка утепленная ",
      brand: "Baon",
      price: 9599,
      rating: "3.7",
      numReview: 3,
      coutnInStocks: 10,
      img: "https://a.lmcdn.ru/img600x866/M/P/MP002XW0CIQ5_16850747_1_v1_2x.jpg",
      description:
        "\n        Куртка утепленная\n        Baon.\n        \n          Утепленная куртка выполнена из тонкого влагоотталкивающего полиэстера. Тонкий слой искусственного утеплителя. Детали: свободный силуэт, карманы на кнопках, шелковистая подкладка.",
    },
    {
      slug: 6,
      name: " Брюки ",
      brand: "Giulia Rossi",
      price: 4594,
      rating: "4.2",
      numReview: 20,
      coutnInStocks: 4,
      img: "https://a.lmcdn.ru/img600x866/M/P/MP002XW03CCF_12340269_1_v2.jpeg",
      description: "\n        Брюки\n        Giulia Rossi.\n        \n      ",
    },
    {
      slug: 7,
      name: " Леггинсы ",
      brand: "Finn Flare",
      price: 2379,
      rating: "3.3",
      numReview: 43,
      coutnInStocks: 20,
      img: "https://a.lmcdn.ru/img600x866/M/P/MP002XW0BMYL_16326529_1_v2.jpeg",
      description: "\n        Леггинсы\n        Finn Flare.\n        \n      ",
    },
    {
      slug: 8,
      name: " Куртка NB Athletics Renew Utility Jacket",
      brand: "New Balance",
      price: 17990,
      rating: "4.2",
      numReview: 2,
      coutnInStocks: 13,
      img: "https://a.lmcdn.ru/img600x866/R/T/RTLABI368201_16854200_1_v1_2x.jpg",
      description:
        "\n        Куртка\n        New Balance.\n        \n          Куртка выполнена из хлопкового материала. Детали: застежка на молнии, воротник-стойка, несъемный капюшон, 2 кармана, удлиненная спинка.",
    },
    {
      slug: 9,
      name: " Юбка ",
      brand: "Top Top",
      price: 4290,
      rating: "4.7",
      numReview: 14,
      coutnInStocks: 19,
      img: "https://a.lmcdn.ru/img600x866/M/P/MP002XW0C7WV_16637634_1_v1_2x.jpeg",
      description: "\n        Юбка\n        Top Top.\n        \n      ",
    },
    {
      slug: 10,
      name: " Джинсы HAVANA",
      brand: "Mango",
      price: 4999,
      rating: "4.0",
      numReview: 40,
      coutnInStocks: 14,
      img: "https://a.lmcdn.ru/img600x866/R/T/RTLABB350201_16215220_1_v1.jpg",
      description: "\n        Джинсы\n        Mango.\n        \n      ",
    },
  ],
};

export default data;
